### ISSUE TITLE
Example of a mapping with a > 22 columns table

### ISSUE THREAD

**Issue by kheraud** [playframework/play-slick#285]
Adding an example with a slick mapping of a > 22 columned table would be very useful (still struggling to make it work).

**Comment by dotta** [comment]
This to me seems something that should be provided in the Slick documentation, rather than the play-slick one. Also, maybe such an example already exist (though, I couldn't easily find it). I'd suggest you to discuss this in the slick mailing list https://groups.google.com/forum/#!forum/scalaquery.

For the above reason, I'm closing the ticket. Please, let me know if you disagree.
