### ISSUE TITLE
Play slick didn't release connection

### ISSUE THREAD

**Issue by hellomaya** [playframework/play-slick#347]
I used "com.typesafe.play" %% "play-slick" % "1.1.1",, and just try something simple by Slick and Play.

When I observe the thread/connection at MySQL server, I found, when the page is loaded, the connection still alive somehow at server side, commonly in Java JDBC access, as I know, if I call ```conn.close()```, the connection will be close, at server side, the thread/connection will appear to be close too.

When I run the app by Play slick, the connection will keep alive even after all data rendered at page, even though the connection number is controlled by HikariCP very stable (never larger than numThreads * 5, default value in Slick), for the database server performance concern, close connection after all data fetched, I think it might be better, or in case I used Slick in a wrong way..

I use Slick this way, and return Future to Play Async Action.

```
def getAll(page: Int, count: Int) = {
  val q = queryTopics.drop(page).take(count)
  db.run(q.result)
}
```

In Play Async Action:

```
def index = Action.async { request => 
  val list = getAll(0, 10)
  list.map {
    item => Ok(item.toString)
  } 
}
```

I also test the ```getAll``` independently at Scala Test case, the connection wasn't release at MySQL server side, which it should if the connection is close by ```conn.close```, I am still reading the Slick source code to know why. I observed the server connection by```mytop``` command at Ubuntu Linux 15 Desktop version with MySQL 5.6.27

**Comment by naderghanbari** [comment]
I'm having the same problem with Play 2.4, Slick 3.1.1 and play-slick 1.1.1. Any help would be appreciated. According to my understanding play-slick automatically closes the connections, is this assumption correct?

**Comment by marcospereira** [comment]
Slick did not closes the connection because there is a connection pooling mechanism, provided by HikariCP.

Instead of always opening a new connection when accessing the database and closing it after using it (which is a very cost operation), HikariCP opens a number of connections and reuse them. So, when play-slick calls `close` it is not really closing the connection, but instead just returning it to the pool.

This is the expected behavior. for version 1.1.1 you can see more information here:

https://github.com/playframework/play-slick/blob/1.1.1/docs/manual/working/scalaGuide/main/sql/slick/PlaySlickAdvancedTopics.md#connection-pool

**Comment by hellomaya** [comment]
@marcospereira 

Thank you! I have got this point.

@naderghanbari 

Yes, it's connection pool.

I explored the code, and then the conclusion is:

Too many connection at MySQL

Compare it with PHP, node-mysql, Java (mysql jdbc), HikariCP, Play!Slick

PHP, node-mysql, Java (JDBC) all fine with connection (conn.close required in Java)

The reason is, it used connection pool, the size of pool is numThreads * 5, so if the numThreads is 10, it will keep 50 connection alive, that quite a lot for a desktop dev Linux distro, also, when we run it with activiator ~run, it will reload the app and re-compile it for any change, this time, the connection will be accumulated as well, so sooner or later, mysql will reject the connection, there are a few way to avoid this, for dev, set numThreads to 1, is ok, and queueSize to be 100 or whatever..

For mysql server, we can add idle time in my.cnf, to force it close the connection after certain time.

**Comment by marcospereira** [comment]
@hellomaya if it is not closing the pool while reloading the app, then this is a bug. Can you confirm this is happening and also with which version of play-slick and Playframework itself?

> PHP, node-mysql, Java (JDBC) all fine with connection (conn.close required in Java)

node.js' mysql lib also has a [connection pool](https://github.com/mysqljs/mysql#pooling-connections) and it is apparently [used by node-mysql](https://github.com/redblaze/node-mysql#new-dbconf). That is because connection pooling is a very common practice. The key here is to set reasonable limits.

> The reason is, it used connection pool, the size of pool is numThreads * 5, so if the numThreads is 10, it will keep 50 connection alive

You can configure the thread pool size according to your needs. But keep in mind that, since JDBC is blocking, if you have more threads than connections, you will end up with a contention (threads waiting for a free pooled connection).

**Comment by hellomaya** [comment]
@marcospereira 

It's quite a long time ago, and the build.st file is here:

https://github.com/hellomaya/scala-connect/blob/master/service/web/build.sbt

It used play-slick 1.1.1, and based on this https://github.com/playframework/play-slick/tree/1.1.x, it could be Slick 3.1.

I didn't dig the reason why it's not closing pool, if do a fresh restart by killing it, that works well.

I just thought it was ```activator ~run``` issue.

Hope this helps.

**Comment by marcospereira** [comment]
@hellomaya this is probably solved.

We had a bug in Play where the connection pool was not being closed when reloading the app. This was solved some time ago (although I was not able to find the issue and pull request now).

Finally, thanks for your time and attention here. :-)

**Comment by hellomaya** [comment]
@marcospereira

It's glad to know this issue was gone, and thank you for your good work! 👍
