### ISSUE TITLE
No close pool connection using dev mode

### ISSUE THREAD

**Issue by Jhara** [playframework/play-slick#350]
When the application runs in dev mode ((run) "auto-reloading enabled") if change code, the compilation phase runs creating a new pool connection and old pool connection doesn´t close.

Tested in H2 database "select \* from information_schema.sessions"

**Comment by lasimon** [comment]
Having same problem with MySQL.  Our dev environment was connected to production (read-only) but the connection pool grew as we were working to the point where it used up all available connections and brought down production.

**Comment by pawankeer** [comment]
+1

**Comment by schmitch** [comment]
On which versions of play are you?

**Comment by pawankeer** [comment]
Using Play 2.4 and Slick 3.1

**Comment by schmitch** [comment]
This issue might be fixed in the latest version.

**Comment by pawankeer** [comment]
Thanks @schmitch. Yeah it's fixed in 2.5.
Is there an update/fix in 2.4 that will fix this problem? It will take me days to update my app to 2.5.

**Comment by richdougherty** [comment]
It looks like the [code in play-slick 1.1.x](https://github.com/playframework/play-slick/blob/1.1.x/src/core/src/main/scala/play/api/db/slick/SlickApi.scala#L102) should be closing the database connection, so it's not clear to me what was fixed in play-slick 2.0. It might require some debugging; it doesn't look like an easy backport unfortunately.

You could try putting a breakpoint into your project to check that the play-slick shutdown code runs properly. That would be useful to know.

**Comment by schmitch** [comment]
@richdougherty I'm not sure about Play 2.4, but in early versions of play 2.5, the database connection wasn't closed if there was a evolution.
https://github.com/playframework/playframework/commit/358a38e54f626ac9750e2211992925e972e8d2b8

Same might be happening in 2.4

**Comment by marcospereira** [comment]
Closing this since there is a fix in Play 2.5.x.
