### ISSUE TITLE
not found: value PlayKeys PlayKeys.playOmnidoc := false

### ISSUE THREAD

**Issue by n0tel** [playframework/play-slick#374]
When i try import sbt project from /samples/basic example, i get:

> play-slick/samples/basic/build.sbt:3: error: not found: value PlayKeys
> PlayKeys.playOmnidoc := false

**Comment by marcospereira** [comment]
Hey @n0tel, importing where?

Keep in mind this is more like a "test" project inside play-slick itself. To see more complete examples, take a look at the following repositories:

1. https://github.com/playframework/play-isolated-slick
2. https://github.com/playframework/play-scala-intro

I'm closing this since you can use these repositories as more complete and functional examples.

**Comment by decapo01** [comment]
Why provide samples to begin with then???   Why not separate them out into separate project if they are not going to work and then provide links to those samples in the documentation?
