### ISSUE TITLE
Publish for Play 2.7 + slick 3.2?

### ISSUE THREAD

**Issue by ashleymercer** [playframework/play-slick#492]
Would it be easy / possible to publish a version that is compatible with Play 2.7, but slick 3.2? 

It looks like there are some moderately serious issues with the new `java.time` support in slick 3.3 (see [here](https://github.com/slick/slick/issues/1987), and [here](https://github.com/slick/slick/issues/2053), and [here](https://github.com/slick/slick/issues/2055), ...) and so not being able to upgrade slick for the time becomes a blocker for upgrading to Play 2.7.

**Comment by renatocaval** [comment]
@ashleymercer, that won't be possible because Play 2.7.x uses a version of Hikari that is incompatible with Slick 3.2.

Basically, Slick 3.2 was using an old version of Hikari and was calling a deprecated method that was then removed. See https://github.com/slick/slick/pull/1821

Play 2.7.x uses a recent version of Hikari and when mixed with Slick 3.2, that removed method is not found and blows up at runtime.

**Comment by ashleymercer** [comment]
Ahh thanks for the explanation - suspected / feared there would be something like this! Fortunately it looks like the slick people are working on making the support for `java.time` optional (or allowing overrides with local implicits) so I'll wait for that work to be finished.
